name: Security & Reports Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_bandit_trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 bandit

      - name: Lint code with flake8
        run: flake8 . --max-line-length=120

      - name: Run Bandit security scan
        run: |
          mkdir -p reports/bandit_reports
          datetime=$(date +"%Y%m%d_%H%M%S")
          bandit -r . -f json -o reports/bandit_reports/bandit_report_$datetime.json

      - name: Run Trivy FS scan
        uses: aquasecurity/trivy-action@v0.33.1
        with:
          scan-type: fs
          format: json
          output: reports/trivy_reports/trivy_fs_report_$(date +%Y%m%d_%H%M%S).json

  docker_trivy_scan:
    runs-on: ubuntu-latest
    needs: lint_bandit_trivy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t my_random_app .

      - name: Run Trivy image scan
        uses: aquasecurity/trivy-action@v0.33.1
        with:
          scan-type: image
          image-ref: my_random_app:latest
          format: json
          output: reports/trivy_reports/trivy_image_report_$(date +%Y%m%d_%H%M%S).json
